server:
  servlet:
    context-path: /mydairy

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  thymeleaf:
    mode: HTML
    servlet:
      content-type: text/html
    cache: false
    encoding: utf-8